Steps of ML Pipeline
1. Data Ingestion / Reading of data
2. EDA
3. Preparation of data
4. Divide the datainto X and Y
5. Train. test and split.
6. Scaling the data OR ML Standardarizatoin. (Optional)
    Don't scale target (i.e. Y)
    Only scale the independence variable.
7. Model Training.
8. Model Evaluation.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from sklearn.datasets import load_diabetes

In [13]:
diabetes = load_diabetes()

In [14]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [17]:
df = pd.DataFrame(diabetes.data, columns = diabetes.feature_names)

In [25]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [26]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [27]:
df.tail()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [28]:
df.shape

(442, 10)

In [31]:
df['target'] = diabetes.target

In [32]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [68]:
X = df[["bmi","age","s1"]]
y = df[["target"]]
x.shape

(442, 1)

In [70]:
X

          bmi       age        s1
0    0.061696  0.038076 -0.044223
1   -0.051474 -0.001882 -0.008449
2    0.044451  0.085299 -0.045599
3   -0.011595 -0.089063  0.012191
4   -0.036385  0.005383  0.003935
..        ...       ...       ...
437  0.019662  0.041708 -0.005697
438 -0.015906 -0.005515  0.049341
439 -0.015906  0.041708 -0.037344
440  0.039062 -0.045472  0.016318
441 -0.073030 -0.045472  0.083740

[442 rows x 3 columns]

In [71]:
y

     target
0     151.0
1      75.0
2     141.0
3     206.0
4     135.0
..      ...
437   178.0
438   104.0
439   132.0
440   220.0
441    57.0

[442 rows x 1 columns]

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 1)

In [74]:
X_train

          bmi
168  0.059541
324  0.005650
41  -0.067641
180  0.004572
162  0.030440
..        ...
255 -0.065486
72  -0.004050
396 -0.030996
235 -0.014828
37   0.011039

[331 rows x 1 columns]

In [75]:
y_test

     target
246    78.0
425   152.0
293   200.0
31     59.0
359   311.0
..      ...
117   281.0
139   281.0
218   214.0
93     96.0
420   146.0

[111 rows x 1 columns]

In [76]:
y_test

     target
246    78.0
425   152.0
293   200.0
31     59.0
359   311.0
..      ...
117   281.0
139   281.0
218   214.0
93     96.0
420   146.0

[111 rows x 1 columns]

In [77]:
y_train

     target
168   268.0
324   249.0
41     55.0
180   107.0
162   172.0
..      ...
255   153.0
72    202.0
396    43.0
235   124.0
37    276.0

[331 rows x 1 columns]

In [78]:
X_test

          bmi
246 -0.032073
425 -0.040696
293  0.092953
31  -0.065486
359  0.005650
..        ...
117 -0.021295
139  0.061696
218 -0.065486
93  -0.064408
420 -0.036385

[111 rows x 1 columns]

In [79]:
X_train.shape

(331, 1)

In [80]:
from sklearn.linear_model import LinearRegression

In [83]:
model = LinearRegression()

In [84]:
model

LinearRegression()

In [85]:
model.fit(X_train,y_train)

LinearRegression()

In [86]:
y_pred = model.predict(X_test)

In [87]:
y_pred

array([[118.87167818],
       [110.11285389],
       [245.87463032],
       [ 84.93123407],
       [157.19153443],
       [171.42462389],
       [229.45183478],
       [135.29447371],
       [128.7253555 ],
       [114.49226604],
       [191.13197853],
       [130.91506157],
       [119.96653121],
       [152.81212228],
       [195.51139067],
       [217.40845139],
       [148.43271014],
       [117.77682514],
       [126.53564943],
       [162.6657996 ],
       [155.00182836],
       [ 98.0694705 ],
       [140.76873889],
       [110.11285389],
       [ 88.21579318],
       [197.70109675],
       [128.7253555 ],
       [192.22683157],
       [112.30255996],
       [163.76065264],
       [145.14815103],
       [150.62241621],
       [207.55477407],
       [117.77682514],
       [ 92.59520532],
       [168.14006478],
       [ 77.26726282],
       [213.02903925],
       [192.22683157],
       [126.53564943],
       [161.57094657],
       [145.14815103],
       [119.96653121],
       [137.48417978],
       [132.00991461],
       [100.25917657],
       [180.18344818],
       [112.30255996],
       [211.93418621],
       [130.91506157],
       [144.053298  ],
       [202.08050889],
       [105.73344175],
       [103.54373568],
       [174.709183  ],
       [136.38932675],
       [158.28638746],
       [119.96653121],
       [ 80.55182193],
       [125.44079639],
       [121.06138425],
       [230.54668782],
       [161.57094657],
       [130.91506157],
       [251.34889549],
       [ 83.83638104],
       [103.54373568],
       [223.9775696 ],
       [194.41653764],
       [ 90.40549925],
       [ 94.78491139],
       [127.63050246],
       [104.63858871],
       [132.00991461],
       [177.9937421 ],
       [ 86.02608711],
       [125.44079639],
       [110.11285389],
       [192.22683157],
       [177.9937421 ],
       [ 94.78491139],
       [122.15623728],
       [140.76873889],
       [142.95844496],
       [ 91.50035229],
       [129.82020853],
       [ 79.45696889],
       [ 95.87976443],
       [314.85037156],
       [135.29447371],
       [151.71726925],
       [163.76065264],
       [139.67388586],
       [ 60.84446729],
       [ 83.83638104],
       [223.9775696 ],
       [117.77682514],
       [128.7253555 ],
       [197.70109675],
       [190.0371255 ],
       [188.94227246],
       [142.95844496],
       [138.57903282],
       [133.10476764],
       [233.83124692],
       [169.23491782],
       [129.82020853],
       [214.12389228],
       [ 84.93123407],
       [ 86.02608711],
       [114.49226604]])

In [92]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [93]:
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

MAE: 52.725578080651374
MSE: 4309.221212879797
R²: 0.17466209865339177

In [99]:
print("Intercept =", model.intercept_)

Intercept = [151.45222564]

In [100]:
print("Coefficient =", model.coef_)

Coefficient = [[1015.81069855]]