In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
diabetes = load_diabetes()

In [4]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'frame': None,
 'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n:Number of Instances: 442\n\n:Number of Attributes: First 10 columns are numeric predictive values\n\n:Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n:Attribute Information:\n    - age     age in years\n    - sex\n    - bmi     body mass index\n    - bp      average blood pressure\n    - s1      tc, total serum cholesterol\n    - s2      ldl, low-density lipoproteins\n    - s3      hdl, high-density lipoproteins\n    - s4      tch, total cholesterol / HDL\n    - s5      ltg, possibly log of serum triglycerides level\n    - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)\n',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'data_filename': 'diabetes_data_raw.csv.gz',
 'target_filename': 'diabetes_target.csv.gz',
 'data_module': 'sklearn.datasets.data'}

In [5]:
df = pd.DataFrame(diabetes.data, columns = diabetes.feature_names)

In [6]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [8]:
df['target'] = diabetes.target

In [9]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [11]:
df = df.drop('target', axis = 1)

In [12]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [13]:
X = df

In [29]:
X

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [31]:
from sklearn.model_selection import train_test_split

In [33]:
X_test, X_train, y_test, y_train = train_test_split(X,y, test_size = 0.25, random_state = 1)

In [34]:
X_test

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
168,0.001751,0.050680,0.059541,-0.002228,0.061725,0.063195,-0.058127,0.108111,0.068986,0.127328
324,0.030811,-0.044642,0.005650,0.011544,0.078236,0.077913,-0.043401,0.108111,0.066051,0.019633
41,-0.099961,-0.044642,-0.067641,-0.108956,-0.074494,-0.072712,0.015505,-0.039493,-0.049872,-0.009362
180,-0.038207,0.050680,0.004572,0.035644,-0.011201,0.005889,-0.047082,0.034309,0.016307,-0.001078
162,-0.052738,-0.044642,0.030440,-0.074527,-0.023584,-0.011335,-0.002903,-0.002592,-0.030748,-0.001078
...,...,...,...,...,...,...,...,...,...,...
255,0.001751,-0.044642,-0.065486,-0.005670,-0.007073,-0.019476,0.041277,-0.039493,-0.003301,0.007207
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492,-0.017646
396,-0.085430,0.050680,-0.030996,-0.022885,-0.063487,-0.054236,0.019187,-0.039493,-0.096435,-0.034215
235,0.067136,0.050680,-0.014828,0.058608,-0.059359,-0.034508,-0.061809,0.012906,-0.005142,0.048628
37,-0.009147,-0.044642,0.011039,-0.057313,-0.024960,-0.042963,0.030232,-0.039493,0.017036,-0.005220

In [36]:
X_test

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
168,0.001751,0.050680,0.059541,-0.002228,0.061725,0.063195,-0.058127,0.108111,0.068986,0.127328
324,0.030811,-0.044642,0.005650,0.011544,0.078236,0.077913,-0.043401,0.108111,0.066051,0.019633
41,-0.099961,-0.044642,-0.067641,-0.108956,-0.074494,-0.072712,0.015505,-0.039493,-0.049872,-0.009362
180,-0.038207,0.050680,0.004572,0.035644,-0.011201,0.005889,-0.047082,0.034309,0.016307,-0.001078
162,-0.052738,-0.044642,0.030440,-0.074527,-0.023584,-0.011335,-0.002903,-0.002592,-0.030748,-0.001078
...,...,...,...,...,...,...,...,...,...,...
255,0.001751,-0.044642,-0.065486,-0.005670,-0.007073,-0.019476,0.041277,-0.039493,-0.003301,0.007207
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084492,-0.017646
396,-0.085430,0.050680,-0.030996,-0.022885,-0.063487,-0.054236,0.019187,-0.039493,-0.096435,-0.034215
235,0.067136,0.050680,-0.014828,0.058608,-0.059359,-0.034508,-0.061809,0.012906,-0.005142,0.048628
37,-0.009147,-0.044642,0.011039,-0.057313,-0.024960,-0.042963,0.030232,-0.039493,0.017036,-0.005220

In [35]:
y_test

     target
168   268.0
324   249.0
41     55.0
180   107.0
162   172.0
..      ...
255   153.0
72    202.0
396    43.0
235   124.0
37    276.0

[331 rows x 1 columns]

In [37]:
y_train

     target
246    78.0
425   152.0
293   200.0
31     59.0
359   311.0
..      ...
117   281.0
139   281.0
218   214.0
93     96.0
420   146.0

[111 rows x 1 columns]

In [21]:
y

     target
0     151.0
1      75.0
2     141.0
3     206.0
4     135.0
..      ...
437   178.0
438   104.0
439   132.0
440   220.0
441    57.0

[442 rows x 1 columns]

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
model = LinearRegression()

In [40]:
model

LinearRegression()

In [42]:
model.fit(X_train,y_train)

LinearRegression()

In [43]:
y_pred = model.predict(X_test)

In [44]:
y_pred

array([[229.3511959 ],
       [212.36599513],
       [ 85.04860264],
       [189.06520627],
       [142.91095566],
       [142.38187362],
       [ 76.80881643],
       [199.853082  ],
       [161.3568523 ],
       [ 55.78379246],
       [218.24844942],
       [208.4749334 ],
       [173.29857001],
       [168.0711625 ],
       [192.69121564],
       [127.24202084],
       [166.32024546],
       [169.41391886],
       [145.15573447],
       [142.97196363],
       [195.41206393],
       [126.99247526],
       [279.84565465],
       [165.2986062 ],
       [187.5323754 ],
       [173.68471925],
       [168.50015795],
       [110.45391805],
       [ 55.63984187],
       [243.96832484],
       [113.57454494],
       [177.20283402],
       [119.86474865],
       [154.69962181],
       [133.93541064],
       [124.83196348],
       [175.1263725 ],
       [186.15798794],
       [180.65926508],
       [231.63018924],
       [178.21974395],
       [191.13973499],
       [146.83062189],
       [154.51608561],
       [116.75910088],
       [183.49797171],
       [185.36872105],
       [ 74.4426346 ],
       [ 56.55864493],
       [140.11652912],
       [159.05707265],
       [139.33271791],
       [ 93.98329436],
       [180.51938204],
       [218.59324071],
       [186.88895609],
       [209.43516599],
       [ 96.59956589],
       [ 76.48020026],
       [168.12387769],
       [186.85761675],
       [101.11556453],
       [181.79772443],
       [ 78.89242812],
       [183.66538719],
       [250.21182516],
       [119.88190413],
       [170.26228103],
       [155.35866418],
       [212.5611534 ],
       [152.9254959 ],
       [213.36855429],
       [108.29344533],
       [202.86620977],
       [147.21543186],
       [128.22736235],
       [192.62656124],
       [181.28935079],
       [139.75358573],
       [121.1043301 ],
       [ 80.47416816],
       [134.56670792],
       [235.18092524],
       [198.71757062],
       [162.57014555],
       [192.84371868],
       [255.66785086],
       [ 97.96457714],
       [133.0763001 ],
       [228.21695304],
       [178.91016505],
       [221.39665808],
       [197.30423748],
       [221.25726823],
       [ 94.75975949],
       [153.7491138 ],
       [ 88.73165114],
       [193.91081484],
       [141.26007967],
       [125.76042435],
       [ 96.23200074],
       [129.32409233],
       [229.58240836],
       [108.68128336],
       [126.32856689],
       [106.16799603],
       [190.17461021],
       [202.82022159],
       [226.69382171],
       [253.81052744],
       [172.33766275],
       [ 76.71114948],
       [159.48312713],
       [ 17.02093158],
       [124.39310097],
       [163.03197118],
       [108.7620804 ],
       [240.78784085],
       [135.40573603],
       [153.6195726 ],
       [129.22456143],
       [175.36191412],
       [143.04263055],
       [ 93.32464921],
       [216.09411222],
       [216.79782214],
       [113.48594806],
       [241.86973126],
       [218.81413034],
       [ 74.25070885],
       [165.32070674],
       [233.10874291],
       [170.09681662],
       [190.91828601],
       [ 90.53255006],
       [217.52212362],
       [170.99087957],
       [ 43.25455567],
       [154.2883456 ],
       [250.08265531],
       [151.9413968 ],
       [225.45503104],
       [202.18328991],
       [254.45129143],
       [167.20017639],
       [132.31097433],
       [242.31258852],
       [ 75.11232217],
       [ 78.91808697],
       [175.09803727],
       [ 71.2973646 ],
       [228.6611747 ],
       [154.64499017],
       [123.49636515],
       [103.22515235],
       [101.79839131],
       [196.39821856],
       [230.67526182],
       [221.98766459],
       [131.56444944],
       [220.60004837],
       [159.35811132],
       [148.62730187],
       [ 83.88177419],
       [235.01661545],
       [178.40916094],
       [232.70606971],
       [160.56654028],
       [206.12064775],
       [224.79662809],
       [137.12015678],
       [213.87813348],
       [156.00232215],
       [189.42965443],
       [207.34907548],
       [198.09027562],
       [170.69647938],
       [222.65306018],
       [209.15994533],
       [130.55524572],
       [155.25230906],
       [154.57667805],
       [ 92.32155992],
       [212.75194083],
       [265.28838315],
       [124.78693294],
       [182.1725344 ],
       [121.16182043],
       [ 33.07212693],
       [140.18378878],
       [136.14186699],
       [161.51616073],
       [173.71486191],
       [121.55463499],
       [177.14158838],
       [ 50.34921267],
       [153.21637769],
       [ 36.5551422 ],
       [246.96953112],
       [ 51.71521045],
       [111.75760648],
       [106.02752986],
       [152.1754271 ],
       [153.98379716],
       [117.59385037],
       [158.7132691 ],
       [215.99264195],
       [165.04276655],
       [103.38148991],
       [ 97.65791122],
       [212.06454954],
       [119.05842551],
       [231.54489   ],
       [ 81.56473177],
       [136.82829328],
       [ 80.33036117],
       [207.3035806 ],
       [223.0927459 ],
       [136.1731205 ],
       [109.7694377 ],
       [143.38123542],
       [106.13940375],
       [ 76.40071512],
       [ 51.34008301],
       [119.83151635],
       [185.56398492],
       [116.53499826],
       [172.88309341],
       [140.05271246],
       [253.94393741],
       [206.01491647],
       [142.53229482],
       [193.57539868],
       [266.68399029],
       [174.28692688],
       [149.33993811],
       [138.24832424],
       [209.80399312],
       [203.67213412],
       [162.9560027 ],
       [138.7908596 ],
       [104.08092964],
       [131.92417995],
       [157.10587005],
       [183.05199455],
       [114.43237729],
       [242.83187956],
       [ 35.62473066],
       [ 70.51241705],
       [ 65.4357644 ],
       [ 54.50487888],
       [152.59723355],
       [255.94431593],
       [203.25390784],
       [ 97.7041786 ],
       [123.56319071],
       [ 50.19649335],
       [174.65756945],
       [148.67099696],
       [268.92928012],
       [132.77421494],
       [128.29671883],
       [143.73974554],
       [ 87.9909471 ],
       [243.21845265],
       [159.68618387],
       [108.07262087],
       [121.00797399],
       [188.25065732],
       [ 87.68685604],
       [172.7897235 ],
       [153.81316247],
       [239.77352113],
       [ 83.21942686],
       [111.02364837],
       [190.58063162],
       [ 84.84590666],
       [170.75142098],
       [179.03794015],
       [191.82269975],
       [197.82722299],
       [ 65.70969466],
       [128.17252727],
       [155.16080451],
       [202.45042457],
       [191.05281557],
       [165.22308239],
       [229.4873043 ],
       [111.62954872],
       [178.1628047 ],
       [201.45176747],
       [122.10054734],
       [ 61.75545705],
       [210.6539263 ],
       [109.37096728],
       [188.88658893],
       [203.30625203],
       [118.05409619],
       [ 57.33725024],
       [239.82401526],
       [ 39.33555447],
       [ 76.6091994 ],
       [126.01758103],
       [262.01719096],
       [124.54994755],
       [159.89955897],
       [170.64163733],
       [125.06723674],
       [148.46612964],
       [174.56604562],
       [177.05110532],
       [161.04033349],
       [201.73307707],
       [229.76525903],
       [188.14978526],
       [ 94.27139887],
       [125.94784959],
       [238.42176959],
       [ 70.68796435],
       [241.50663779],
       [222.5948801 ],
       [179.14524806],
       [ 85.74386043],
       [ 68.87554864],
       [204.50315633],
       [108.10398743],
       [134.28484756],
       [140.04753117],
       [ 52.9253918 ],
       [185.49374285],
       [163.95350097]])

In [45]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [51]:
print("MSE" , mean_squared_error(y_test, y_pred))
print("MAE" , mean_absolute_error(y_test, y_pred))
print("R_square ", r2_score(y_test, y_pred))

MSE 3019.5396882687455
MAE 45.069736655982915
R_square  0.5096819400188017

In [48]:
print("Intercept =", model.intercept_)

Intercept = [154.28574022]

In [49]:
print("Coefficient =", model.coef_)

Coefficient = [[  -51.97598184  -212.85849381   367.3942985    314.7910588
  -1834.37961522  1390.28051165   504.13682355   184.60084415
   1195.49961742   133.61686528]]

In [50]:
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064